/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LEDlib;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        LEDPerimeter classUnderTest = new LEDPerimeter(24,32);
    }
}
